version: '3.7'

networks: 
  local:
    driver: bridge

services:

  mongodb:
    container_name: mongodb
    networks:
      - local
    image: mongo

  back:
    container_name: back
    networks: 
      - local
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: back.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back/:/usr/src/app
    working_dir: /usr/src/app
    links:
      - mongodb

  front:
    container_name: front
    networks: 
      - local
    depends_on:
      - back
    build:
      context: .
      dockerfile: front.dockerfile
    ports:
      - "4200:8080"
    volumes:
      - ./front/:/app
    working_dir: /app
    command: npm start